name: Daily News Email

on:
  schedule:
    - cron: "20 * * * *"
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scripts
        run: |
          python google_topstories_test.py
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Commit seen_news.json
        run: |
          git add seen_news.json
          git commit -m "Update seen news cache" || echo "No changes to commit"
          git push
